const PRODUCTS=[
{name:'CeraVe Foaming Facial Cleanser',key:'cleanser',local:'images/cleanser.png',use:'Gentle cleanse',when:'AM + PM'},
{name:'Garnier Vitamin C Serum',key:'vitc',local:'images/vitamin-c.png',use:'Bright/even-looking skin support',when:'AM'},
{name:'The Ordinary Niacinamide 10% + Zinc 1%',key:'niacinamide',local:'images/niacinamide.png',use:'Oil + uneven-tone support',when:'Normal PM'},
{name:'The Ordinary Azelaic Acid 10%',key:'azelaic',local:'images/azelaic.png',use:'Uneven-tone appearance support',when:'Azelaic PM'},
{name:'CeraVe Daily Moisturizing Lotion',key:'moisturizer',local:'images/moisturizer.png',use:'Moisture + barrier support',when:'AM + PM'},
{name:'La Roche-Posay Anthelios SPF50+',key:'spf',local:'images/sunscreen.png',use:'Daily sun protection',when:'AM + outdoors'}];
const AZELAIC_DAYS=[3,6,10,13,17,20,24,27,30], STORAGE_KEY='skinRoutineState', PHOTO_DB='skinRoutinePhotosV3', PHOTO_STORE='photos';
const iso=()=>new Date().toISOString().slice(0,10), dObj=s=>new Date(s+'T00:00:00'), esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function def(){return{startDate:iso(),completed:{},morningTime:'08:00',nightTime:'22:00',theme:'light',photoDays:{},notifications:false,lastReminder:{}}}
function migrate(c){const out={};for(const [k,a0] of Object.entries(c||{})){const day=k.replace(/^day-/,'');const a=Array.isArray(a0)?a0:[],n=new Set();for(const id of a){if(id==='cleanser')n.add('morning-cleanser');else if(id==='moisturizer')n.add('morning-moisturizer');else if(id==='vitc')n.add('morning-vitc');else if(id==='spf')n.add('morning-spf');else if(id==='niacinamide')n.add('night-niacinamide');else if(id==='azelaic')n.add('night-azelaic');else n.add(id)}out['day-'+day]=[...n]}return out}
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!s)return def();return {...def(),...s,completed:migrate(s.completed),photoDays:s.photoDays||{}}}catch{return def()}}
let state=load(),currentTab='today',previewDay=null,deferredInstall=null,photoTarget=null,urls={};
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const currentDay=()=>Math.max(1,Math.min(30,Math.floor((dObj(iso())-dObj(state.startDate))/86400000)+1));
const az=d=>AZELAIC_DAYS.includes(d), routine=d=>({morning:[['morning-cleanser','Cleanser'],['morning-vitc','Vitamin C'],['morning-moisturizer','Moisturizer'],['morning-spf','SPF 50+']],night:[['night-cleanser','Cleanser'],[az(d)?'night-azelaic':'night-niacinamide',az(d)?'Azelaic Acid':'Niacinamide'],['night-moisturizer','Moisturizer'] ]});
const doneSet=d=>new Set(state.completed['day-'+d]||[]);
function toggle(day,id){const k='day-'+day,s=doneSet(day);s.has(id)?s.delete(id):s.add(id);state.completed[k]=[...s];save();render()}
window.toggle=toggle;
const all=d=>[...routine(d).morning,...routine(d).night], pct=d=>Math.round(doneSet(d).size/all(d).length*100), completedDays=()=>Array.from({length:30},(_,i)=>pct(i+1)===100).filter(Boolean).length;
function streak(){let n=0;for(let d=Math.min(30,currentDay());d>=1&&pct(d)===100;d--)n++;return n}
function planDate(d){const x=dObj(state.startDate);x.setDate(x.getDate()+d-1);return x.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}
function task(d,id,label){const yes=doneSet(d).has(id);return `<button class="task-v5 ${yes?'done':''}" onclick="toggle(${d},'${id}')"><span class="tick">${yes?'✓':''}</span><span><b>${label}</b><small>${id.includes('spf')?'Sun protection':id.includes('vitc')?'Serum':id.includes('azelaic')?'Selected night':id.includes('niacinamide')?'Normal night':id.includes('cleanser')?'Gentle cleanse':'Moisturise'}</small></span></button>`}
function today(){const d=previewDay||currentDay(),r=routine(d),ds=doneSet(d),m=r.morning.filter(x=>ds.has(x[0])).length,n=r.night.filter(x=>ds.has(x[0])).length,p=pct(d);return `<div class="home-v5"><header class="home-head"><div><span class="eyebrow-v5">30 DAY SKIN ROUTINE</span><h2>${previewDay?'Day '+d:'Today'} <span>· ${planDate(d)}</span></h2><p>${p===100?'Routine complete 🎉':p>0?'Keep going — you are doing great.':'Small steps, every day.'}</p></div><div class="day-bubble"><b>${d}</b><small>/30</small></div></header><div class="summary-v5"><div><b>${p}%</b><small>complete</small></div><div class="bar-v5"><i style="width:${p}%"></i></div><div class="summary-stat"><b>${streak()}</b><small>streak</small></div></div><div class="columns-v5"><section><div class="col-head"><span>☀️</span><div><b>Morning</b><small>${m}/4 done</small></div></div>${r.morning.map(x=>task(d,x[0],x[1])).join('')}</section><section><div class="col-head"><span>🌙</span><div><b>Night</b><small>${az(d)?'Azelaic':'Niacinamide'}</small></div></div>${r.night.map(x=>task(d,x[0],x[1])).join('')}</section></div><div class="friendly-tip"><span>☀️</span><div><b>SPF 50+ every morning</b><small>Reapply when outdoors or sweating.</small></div></div>${previewDay?'<button class="back-v5" onclick="previewDay=null;render(\'days\')">← Back to days</button>':''}</div>`}
function days(){const d=currentDay();return `<div class="tab-v5"><header><div><span class="eyebrow-v5">YOUR PLAN</span><h2>30 Days</h2></div><span class="mini-chip">${completedDays()}/30 done</span></header><div class="days-v5">${Array.from({length:30},(_,i)=>{const n=i+1,p=pct(n);return `<button class="day-v5 ${p===100?'done':''} ${n===d?'today':''}" onclick="previewDay=${n};render('today')"><b>${n}</b><small>${p===100?'✓':p+'%'}</small></button>`}).join('')}</div><div class="tiny-note">🌙 Azelaic nights: ${AZELAIC_DAYS.join(', ')} · other nights use Niacinamide.</div></div>`}
function products(){return `<div class="tab-v5"><header><div><span class="eyebrow-v5">YOUR ROUTINE</span><h2>Products</h2></div><span class="mini-chip">6 steps</span></header><div class="products-v5">${PRODUCTS.map(p=>`<article><div class="p-img"><img src="${p.local}" alt="${esc(p.name)}"></div><b>${esc(p.name)}</b><small>${esc(p.when)} · ${esc(p.use)}</small></article>`).join('')}</div></div>`}
function photoCard(d){const has=!!state.photoDays[d];return `<div class="photo-v5"><div class="photo-box-v5" id="photo-${d}">${has?'Loading…':'Day '+d}</div><button onclick="choosePhoto(${d})">${has?'Replace':'Add photo'}</button>${has?`<button class="remove" onclick="removePhoto(${d})">Remove</button>`:''}</div>`}
function progress(){const cd=completedDays(),p=Math.round(cd/30*100);return `<div class="tab-v5 progress-v5"><header><div><span class="eyebrow-v5">YOUR PROGRESS</span><h2>Progress</h2></div><span class="mini-chip">${p}%</span></header><div class="progress-summary"><b>${cd}<small>/30</small></b><span>fully completed days</span><div class="bar-v5"><i style="width:${p}%"></i></div><em>🔥 ${streak()} day streak</em></div><div class="photo-title"><b>📸 Progress photos</b><small>Day 1 · 15 · 30</small></div><div class="photos-v5">${[1,15,30].map(photoCard).join('')}</div><div class="tiny-note">Use similar lighting, distance and angle for better comparison.</div></div>`}
async function render(tab=currentTab){if(tab)currentTab=tab;document.body.className=currentTab==='today'?'home-screen-v5':'';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===currentTab));const s=document.getElementById('screen');s.innerHTML=currentTab==='today'?today():currentTab==='days'?days():currentTab==='products'?products():progress();applyTheme();if(currentTab==='progress')await hydratePhotos()}
function applyTheme(){document.documentElement.dataset.theme=state.theme||'light';updateTheme()}
function updateTheme(){const b=document.getElementById('themeBtn');if(b)b.textContent='🌙 Dark mode: '+(state.theme==='dark'?'ON':'OFF')}
function openSettings(){for(const id of ['startDate','morningTime','nightTime'])document.getElementById(id).value=state[id];updateTheme();document.getElementById('notifyBtn').textContent=Notification.permission==='granted'?'🔔 Notifications ON · Test':'🔔 Enable notifications';document.getElementById('modal').classList.remove('hidden')}
function closeSettings(){document.getElementById('modal').classList.add('hidden')}
function notify(title,body){if('Notification' in window&&Notification.permission==='granted')new Notification(title,{body,icon:'icons/icon-192.png',tag:'skin-routine'})}
async function enableNotifications(){if(!('Notification' in window)){alert('Notifications are not supported in this browser.');return}try{const p=await Notification.requestPermission();state.notifications=p==='granted';save();if(p==='granted'){notify('Skin Routine','Notifications are enabled. You will get reminders while the app is active.');scheduleNext();}else alert('Notification permission was not granted. Please allow notifications for this site in browser settings.')}catch(e){alert('Please open this app in Chrome or Samsung Internet and allow notifications.')}openSettings()}
let timer=null;function scheduleNext(){clearTimeout(timer);if(Notification.permission!=='granted')return;const now=new Date(), candidates=[];for(const [label,t] of [['Morning',state.morningTime],['Night',state.nightTime]]){const [h,m]=t.split(':').map(Number),x=new Date(now);x.setHours(h,m,0,0);if(x<=now)x.setDate(x.getDate()+1);candidates.push([x,label])}candidates.sort((a,b)=>a[0]-b[0]);const [when,label]=candidates[0];timer=setTimeout(()=>{notify(label+' skincare','Time for your '+label.toLowerCase()+' routine.');scheduleNext()},Math.max(1000,when-now))}
function choosePhoto(d){photoTarget=d;const i=document.getElementById('photoInput');i.value='';i.click()}
async function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(PHOTO_DB,1);q.onupgradeneeded=()=>q.result.createObjectStore(PHOTO_STORE);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putPhoto(d,b){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(PHOTO_STORE,'readwrite');t.objectStore(PHOTO_STORE).put(b,String(d));t.oncomplete=()=>{db.close();res()};t.onerror=()=>rej(t.error)})}
async function getPhoto(d){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(PHOTO_STORE).objectStore(PHOTO_STORE).get(String(d));q.onsuccess=()=>{db.close();res(q.result)};q.onerror=()=>rej(q.error)})}
async function delPhoto(d){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(PHOTO_STORE,'readwrite');t.objectStore(PHOTO_STORE).delete(String(d));t.oncomplete=()=>{db.close();res()};t.onerror=()=>rej(t.error)})}
async function hydratePhotos(){for(const d of [1,15,30])if(state.photoDays[d]){try{const b=await getPhoto(d),box=document.getElementById('photo-'+d);if(b&&box){if(urls[d])URL.revokeObjectURL(urls[d]);urls[d]=URL.createObjectURL(b);box.innerHTML=`<img src="${urls[d]}" alt="Day ${d}">`}}catch{}}}
async function removePhoto(d){await delPhoto(d).catch(()=>{});delete state.photoDays[d];save();render('progress')}
function compress(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1200,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>b?res(b):rej(), 'image/jpeg',.82)};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(f)})}
document.getElementById('photoInput').onchange=async e=>{const f=e.target.files?.[0];if(!f||!photoTarget)return;try{await putPhoto(photoTarget,await compress(f));state.photoDays[photoTarget]=true;save();render('progress')}catch{alert('Photo save failed. Please try another image.')}};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{previewDay=null;render(b.dataset.tab)});document.getElementById('settingsBtn').onclick=openSettings;document.getElementById('closeModal').onclick=closeSettings;document.getElementById('startDate').onchange=e=>{state.startDate=e.target.value;save();previewDay=null;render('today')};document.getElementById('morningTime').onchange=e=>{state.morningTime=e.target.value;save();scheduleNext()};document.getElementById('nightTime').onchange=e=>{state.nightTime=e.target.value;save();scheduleNext()};document.getElementById('themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};document.getElementById('notifyBtn').onclick=enableNotifications;document.getElementById('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else alert('Browser menu → Install app / Add to Home screen ഉപയോഗിക്കുക.');};document.getElementById('resetBtn').onclick=async()=>{if(confirm('Reset routine progress and photos?')){for(const d of [1,15,30])await delPhoto(d).catch(()=>{});const keep={startDate:state.startDate,morningTime:state.morningTime,nightTime:state.nightTime,theme:state.theme};state={...def(),...keep};save();closeSettings();render('today')}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.addEventListener('focus',()=>{scheduleNext();});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js?v=5').then(r=>r.update()).catch(()=>{}));applyTheme();render('today');scheduleNext();
