const PRODUCTS=[
{name:'CeraVe Foaming Cleanser',key:'cleanser',local:'images/cleanser.svg',when:'AM + PM',short:'Cleanse'},
{name:'Garnier Vitamin C Serum',key:'vitc',local:'images/vitamin-c.svg',when:'AM',short:'Serum'},
{name:'The Ordinary Niacinamide 10% + Zinc 1%',key:'niacinamide',local:'images/niacinamide.svg',when:'PM',short:'Normal nights'},
{name:'The Ordinary Azelaic Acid 10%',key:'azelaic',local:'images/azelaic.svg',when:'Selected PM',short:'Azelaic nights'},
{name:'CeraVe Daily Moisturizing Lotion',key:'moisturizer',local:'images/moisturizer.svg',when:'AM + PM',short:'Moisturise'},
{name:'La Roche-Posay Anthelios SPF50+',key:'spf',local:'images/sunscreen.svg',when:'AM + outdoors',short:'Sun protection'}
];
const AZELAIC_DAYS=[3,6,10,13,17,20,24,27,30];
const STORAGE_KEY='skinRoutineState', PHOTO_DB='skinRoutinePhotosV3', PHOTO_STORE='photos';
const iso=()=>new Date().toISOString().slice(0,10), dObj=s=>new Date(s+'T00:00:00');
const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function def(){return{startDate:iso(),completed:{},morningTime:'08:00',nightTime:'22:00',theme:'light',photoDays:{},notifications:false,lastReminder:{}}}
function migrate(c){const out={};for(const [k,a0] of Object.entries(c||{})){const day=k.replace(/^day-/,'');const a=Array.isArray(a0)?a0:[],n=new Set();for(const id of a){const map={cleanser:'morning-cleanser',moisturizer:'morning-moisturizer',vitc:'morning-vitc',spf:'morning-spf',niacinamide:'night-niacinamide',azelaic:'night-azelaic'};n.add(map[id]||id)}out['day-'+day]=[...n]}return out}
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!s)return def();return {...def(),...s,completed:migrate(s.completed),photoDays:s.photoDays||{}}}catch{return def()}}
let state=load(),currentTab='today',previewDay=null,deferredInstall=null,photoTarget=null,urls={},timer=null;
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const currentDay=()=>Math.max(1,Math.min(30,Math.floor((dObj(iso())-dObj(state.startDate))/86400000)+1));
const az=d=>AZELAIC_DAYS.includes(d);
const routine=d=>({morning:[['morning-cleanser','Cleanser'],['morning-vitc','Vitamin C'],['morning-moisturizer','Moisturizer'],['morning-spf','SPF 50+']],night:[['night-cleanser','Cleanser'],[az(d)?'night-azelaic':'night-niacinamide',az(d)?'Azelaic Acid':'Niacinamide'],['night-moisturizer','Moisturizer']]});
const doneSet=d=>new Set(state.completed['day-'+d]||[]);
function toggle(day,id){const k='day-'+day,s=doneSet(day);s.has(id)?s.delete(id):s.add(id);state.completed[k]=[...s];save();render(currentTab)}
const all=d=>[...routine(d).morning,...routine(d).night], pct=d=>Math.round(doneSet(d).size/all(d).length*100);
const completedDays=()=>Array.from({length:30},(_,i)=>pct(i+1)===100).filter(Boolean).length;
function streak(){let n=0;for(let d=Math.min(30,currentDay());d>=1&&pct(d)===100;d--)n++;return n}
function planDate(d){const x=dObj(state.startDate);x.setDate(x.getDate()+d-1);return x.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}
function task(d,id,label){const yes=doneSet(d).has(id);return `<button type="button" class="task task-v6 ${yes?'done':''}" data-day="${d}" data-id="${esc(id)}"><span class="tick">${yes?'✓':''}</span><span class="task-copy"><b>${label}</b><small>${id.includes('spf')?'Sun protection':id.includes('vitc')?'Brightening serum':id.includes('azelaic')?'Selected night':id.includes('niacinamide')?'Normal night':id.includes('cleanser')?'Gentle cleanse':'Barrier moisture'}</small></span></button>`}
function productCard(p){return `<article class="product-card"><div class="product-img"><img src="${p.local}" alt="${esc(p.name)}" onerror="this.onerror=null;this.src='images/${p.key}.png'"></div><div class="product-info"><b>${esc(p.name)}</b><span>${esc(p.when)}</span><small>${esc(p.short)}</small></div></article>`}
function today(){const d=previewDay||currentDay(),r=routine(d),ds=doneSet(d),m=r.morning.filter(x=>ds.has(x[0])).length,n=r.night.filter(x=>ds.has(x[0])).length,p=pct(d);return `<div class="home">
<header class="home-head"><div><div class="eyebrow">${previewDay?'PLAN PREVIEW':'TODAY'}</div><h2>${previewDay?'Day '+d:'Good day'} <span>· ${planDate(d)}</span></h2><p>${p===100?'All done — great job! 🎉':p>0?'Keep going. You are on track.':'A simple routine, one step at a time.'}</p></div><div class="day-ring"><strong>${d}</strong><small>/30</small></div></header>
<section class="progress-strip"><div><strong>${p}%</strong><small>today</small></div><div class="progress-line"><i style="width:${p}%"></i></div><div class="stat"><strong>${streak()}</strong><small>streak</small></div></section>
<section class="routine-grid">
<div class="routine-card morning"><div class="routine-head"><span class="routine-icon">☀️</span><div><b>Morning</b><small>${m}/4 complete</small></div></div>${r.morning.map(x=>task(d,x[0],x[1])).join('')}</div>
<div class="routine-card night"><div class="routine-head"><span class="routine-icon">🌙</span><div><b>Night</b><small>${n}/3 · ${az(d)?'Azelaic night':'Niacinamide night'}</small></div></div>${r.night.map(x=>task(d,x[0],x[1])).join('')}</div>
</section>
<section class="products-home"><div class="section-title"><div><b>Your products</b><small>Use in the order shown</small></div><span>6 steps</span></div><div class="product-grid">${PRODUCTS.map(productCard).join('')}</div></section>
<div class="sun-tip"><span>☀️</span><div><b>SPF 50+ every morning</b><small>Reapply when outdoors or sweating.</small></div></div>
${previewDay?'<button class="back-btn" id="backToDays">← Back to 30 days</button>':''}
</div>`}
function days(){const d=currentDay();return `<div class="tab"><header><div><div class="eyebrow">YOUR PLAN</div><h2>30 Days</h2><p>Tap a day to see its routine.</p></div><span class="chip">${completedDays()}/30 done</span></header><div class="days-grid">${Array.from({length:30},(_,i)=>{const n=i+1,p=pct(n);return `<button type="button" class="day-card ${p===100?'done':''} ${n===d?'today':''}" data-preview="${n}"><strong>${n}</strong><small>${p===100?'✓':p+'%'}</small></button>`}).join('')}</div><div class="tab-note">🌙 Azelaic nights: ${AZELAIC_DAYS.join(', ')} · other nights use Niacinamide.</div></div>`}
function photoCard(d){const has=!!state.photoDays[d];return `<div class="photo-card"><div class="photo-box" id="photo-${d}">${has?'Loading…':'Day '+d}</div><button type="button" class="photo-btn" data-photo="${d}">${has?'Replace photo':'Add photo'}</button>${has?`<button type="button" class="remove-btn" data-remove-photo="${d}">Remove</button>`:''}</div>`}
function progress(){const cd=completedDays(),p=Math.round(cd/30*100);return `<div class="tab progress-tab"><header><div><div class="eyebrow">YOUR PROGRESS</div><h2>Progress</h2><p>Keep your routine consistent.</p></div><span class="chip">${p}%</span></header><section class="progress-card"><div class="big-number"><strong>${cd}</strong><small>/30 days</small></div><div><b>Completed days</b><small>🔥 ${streak()} day streak</small></div><div class="progress-line wide"><i style="width:${p}%"></i></div></section><div class="photo-title"><b>📸 Progress photos</b><small>Day 1 · 15 · 30</small></div><div class="photos">${[1,15,30].map(photoCard).join('')}</div><div class="tab-note">Use similar lighting, distance and angle for a fair visual comparison.</div></div>`}
async function render(tab=currentTab){if(tab)currentTab=tab;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===currentTab));const s=document.getElementById('screen');s.innerHTML=currentTab==='today'?today():currentTab==='days'?days():progress();applyTheme();if(currentTab==='progress')await hydratePhotos();}
function applyTheme(){document.documentElement.dataset.theme=state.theme||'light';updateTheme()}
function updateTheme(){const b=document.getElementById('themeBtn');if(b)b.textContent='🌙 Dark mode: '+(state.theme==='dark'?'ON':'OFF')}
function updateNotifyStatus(){const el=document.getElementById('notifyStatus'),btn=document.getElementById('notifyBtn');if(!('Notification'in window)){el.textContent='Notifications: not supported in this browser';btn.textContent='🔔 Notifications unavailable';return}const p=Notification.permission;el.textContent=p==='granted'?'Notifications: ON ✓':p==='denied'?'Notifications: BLOCKED — allow this site in browser settings':'Notifications: not enabled';btn.textContent=p==='granted'?'🔔 Test notification':'🔔 Enable & Test Notification'}
function openSettings(){document.getElementById('startDate').value=state.startDate;document.getElementById('morningTime').value=state.morningTime;document.getElementById('nightTime').value=state.nightTime;updateTheme();updateNotifyStatus();document.getElementById('modal').classList.remove('hidden')}
function closeSettings(){document.getElementById('modal').classList.add('hidden')}
async function showNotification(title,body){try{if(!('Notification'in window))throw new Error('unsupported');if(Notification.permission!=='granted')return false;const reg=await navigator.serviceWorker?.ready;if(reg&&reg.showNotification){await reg.showNotification(title,{body,icon:'icons/icon-192.png',badge:'icons/icon-192.png',tag:'skin-routine',renotify:true});return true}new Notification(title,{body,icon:'icons/icon-192.png',tag:'skin-routine'});return true}catch(e){return false}}
async function enableNotifications(){if(!('Notification'in window)){alert('ഈ browser notifications support ചെയ്യുന്നില്ല. Chrome അല്ലെങ്കിൽ Samsung Internet ഉപയോഗിക്കുക.');return}if(Notification.permission==='denied'){alert('Notifications BLOCKED ആണ്. Browser → Site settings → Notifications → Allow ചെയ്യുക.');updateNotifyStatus();return}const p=await Notification.requestPermission();state.notifications=p==='granted';save();if(p==='granted'){const ok=await showNotification('Skin Routine ✓','Notification is working. Your reminders are enabled.');if(!ok)alert('Notification test failed. Please check site notification permission.');scheduleNext()}else alert('Notification permission അനുവദിച്ചിട്ടില്ല.');updateNotifyStatus()}
function nextReminder(){const now=new Date(),arr=[];for(const [label,t] of [['Morning',state.morningTime],['Night',state.nightTime]]){const [h,m]=t.split(':').map(Number),x=new Date(now);x.setHours(h,m,0,0);if(x<=now)x.setDate(x.getDate()+1);arr.push([x,label])}arr.sort((a,b)=>a[0]-b[0]);return arr[0]}
function scheduleNext(){clearTimeout(timer);if(Notification.permission!=='granted')return;const [when,label]=nextReminder();timer=setTimeout(async()=>{await showNotification(label+' skincare','Time for your '+label.toLowerCase()+' routine.');scheduleNext()},Math.max(1000,when-Date.now()))}
function choosePhoto(d){photoTarget=d;const i=document.getElementById('photoInput');i.value='';i.click()}
async function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(PHOTO_DB,1);q.onupgradeneeded=()=>q.result.createObjectStore(PHOTO_STORE);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putPhoto(d,b){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(PHOTO_STORE,'readwrite');t.objectStore(PHOTO_STORE).put(b,String(d));t.oncomplete=()=>{db.close();res()};t.onerror=()=>rej(t.error)})}
async function getPhoto(d){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(PHOTO_STORE).objectStore(PHOTO_STORE).get(String(d));q.onsuccess=()=>{db.close();res(q.result)};q.onerror=()=>rej(q.error)})}
async function delPhoto(d){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(PHOTO_STORE,'readwrite');t.objectStore(PHOTO_STORE).delete(String(d));t.oncomplete=()=>{db.close();res()};t.onerror=()=>rej(t.error)})}
async function hydratePhotos(){for(const d of [1,15,30])if(state.photoDays[d]){try{const b=await getPhoto(d),box=document.getElementById('photo-'+d);if(b&&box){if(urls[d])URL.revokeObjectURL(urls[d]);urls[d]=URL.createObjectURL(b);box.innerHTML=`<img src="${urls[d]}" alt="Day ${d}">`}}catch{}}}
async function removePhoto(d){await delPhoto(d).catch(()=>{});delete state.photoDays[d];save();render('progress')}
function compress(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1200,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>b?res(b):rej(), 'image/jpeg',.82)};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(f)})}
document.getElementById('photoInput').onchange=async e=>{const f=e.target.files?.[0];if(!f||!photoTarget)return;try{await putPhoto(photoTarget,await compress(f));state.photoDays[photoTarget]=true;save();render('progress')}catch{alert('Photo save failed. Please try another image.')}};
document.getElementById('screen').addEventListener('click',e=>{const taskBtn=e.target.closest('[data-id]');if(taskBtn){toggle(Number(taskBtn.dataset.day),taskBtn.dataset.id);return}const day=e.target.closest('[data-preview]');if(day){previewDay=Number(day.dataset.preview);render('today');return}const photo=e.target.closest('[data-photo]');if(photo){choosePhoto(Number(photo.dataset.photo));return}const rem=e.target.closest('[data-remove-photo]');if(rem){removePhoto(Number(rem.dataset.removePhoto));return}if(e.target.closest('#backToDays')){previewDay=null;render('days')}});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{previewDay=null;render(b.dataset.tab)});
document.getElementById('settingsBtn').onclick=openSettings;document.getElementById('closeModal').onclick=closeSettings;
document.getElementById('startDate').onchange=e=>{state.startDate=e.target.value;save();previewDay=null;render('today')};
document.getElementById('morningTime').onchange=e=>{state.morningTime=e.target.value;save();scheduleNext()};document.getElementById('nightTime').onchange=e=>{state.nightTime=e.target.value;save();scheduleNext()};
document.getElementById('themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};document.getElementById('notifyBtn').onclick=enableNotifications;
document.getElementById('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else alert('Browser menu → Install app / Add to Home screen ഉപയോഗിക്കുക.')};
document.getElementById('resetBtn').onclick=async()=>{if(confirm('Reset routine progress and photos?')){for(const d of [1,15,30])await delPhoto(d).catch(()=>{});const keep={startDate:state.startDate,morningTime:state.morningTime,nightTime:state.nightTime,theme:state.theme};state={...def(),...keep};save();closeSettings();render('today')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.addEventListener('focus',()=>{scheduleNext()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js?v=6').then(r=>r.update()).catch(()=>{}));
applyTheme();render('today');scheduleNext();
