const PRODUCTS={
 cleanser:{name:'CeraVe Foaming Facial Cleanser',img:'https://africa.cerave.com/en/-/media/Project/Loreal/BrandSites/CeraVe/Master/US/Product/cleansers/Gallery/Foaming-Cleanser-Front-420X420-v1.png'},
 vitc:{name:'Garnier Vitamin C Brightening Serum',img:'https://static.chemistwarehouse.com.au/ams/media/pi/154887/ADD3_800.jpg'},
 niacinamide:{name:'The Ordinary Niacinamide 10% + Zinc 1%',img:'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwce8a7cdf/Images/products/The%20Ordinary/rdn-niacinamide-10pct-zinc-1pct-30ml.png?sh=800&sm=fit&sw=800'},
 azelaic:{name:'The Ordinary Azelaic Acid Suspension 10%',img:'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw711cec9a/Images/products/The%20Ordinary/rdn-azelaic-acid-suspension-10pct-30ml.png?sh=800&sm=fit&sw=800'},
 moisturizer:{name:'CeraVe Daily Moisturizing Lotion',img:'https://africa.cerave.com/en/-/media/Project/Loreal/BrandSites/CeraVe/Master/US/Product/Moisturizers/Gallery/Daily_Moisturizing_Lotion_12oz_FRONT_010_v3_CLNT.png'},
 spf:{name:'La Roche-Posay Anthelios UVMune 400 SPF50+',img:'https://africa.laroche-posay.com/-/media/project/loreal/brand-sites/lrp/emea/za/products/anthelios/uvmune-fluid-non-perfumed/lrpproductpagesunantheliosuvmune400fluidspspf503337875797597frontpng.png?sc_lang=en-za'}
};
const AZELAIC_DAYS=[3,6,10,13,17,20,24,27,30],STORAGE_KEY='skinRoutineState',PHOTO_DB='skinRoutinePhotosV3',PHOTO_STORE='photos';
const iso=()=>new Date().toISOString().slice(0,10),dObj=s=>new Date(s+'T00:00:00');
function def(){return{startDate:iso(),completed:{},morningTime:'08:00',nightTime:'22:00',theme:'light',photoDays:{},notifications:false,lastReminder:{}}}
function migrate(c){const out={};for(const[k,a0]of Object.entries(c||{})){const day=k.replace(/^day-/,'');const a=Array.isArray(a0)?a0:[],n=new Set();for(const id of a){const map={cleanser:'morning-cleanser',moisturizer:'morning-moisturizer',vitc:'morning-vitc',spf:'morning-spf',niacinamide:'night-niacinamide',azelaic:'night-azelaic'};n.add(map[id]||id)}out['day-'+day]=[...n]}return out}
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!s)return def();return{...def(),...s,completed:migrate(s.completed),photoDays:s.photoDays||{}}}catch{return def()}}
let state=load(),currentTab='today',previewDay=null,deferredInstall=null,photoTarget=null,urls={},timer=null,touchX=0;
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const currentDay=()=>Math.max(1,Math.min(30,Math.floor((dObj(iso())-dObj(state.startDate))/86400000)+1));
const az=d=>AZELAIC_DAYS.includes(d);
const routine=d=>({morning:[['morning-cleanser','Cleanser','cleanser','Gentle cleanse'],['morning-vitc','Vitamin C','vitc','Brightening serum'],['morning-moisturizer','Moisturizer','moisturizer','Barrier moisture'],['morning-spf','SPF 50+','spf','Sun protection']],night:[['night-cleanser','Cleanser','cleanser','Gentle cleanse'],[az(d)?'night-azelaic':'night-niacinamide',az(d)?'Azelaic Acid':'Niacinamide',az(d)?'azelaic':'niacinamide',az(d)?'Selected night':'Normal night'],['night-moisturizer','Moisturizer','moisturizer','Barrier moisture']]});
const doneSet=d=>new Set(state.completed['day-'+d]||[]);
function toggle(day,id){const k='day-'+day,s=doneSet(day);s.has(id)?s.delete(id):s.add(id);state.completed[k]=[...s];save();render('today')}
const all=d=>[...routine(d).morning,...routine(d).night],pct=d=>Math.round(doneSet(d).size/all(d).length*100),completedDays=()=>Array.from({length:30},(_,i)=>pct(i+1)===100).filter(Boolean).length;
const PHOTO_MILESTONES=[5,10,15,20,25,30];
const photoReminderDue=()=>PHOTO_MILESTONES.some(d=>currentDay()>=d && !state.photoDays[d]);
function streak(){let n=0;for(let d=Math.min(30,currentDay());d>=1&&pct(d)===100;d--)n++;return n}
function planDate(d){const x=dObj(state.startDate);x.setDate(x.getDate()+d-1);return x.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}
function imgTag(key,cls='task-img'){const p=PRODUCTS[key];return `<span class="${cls}"><img src="${p.img}" alt="${p.name}" data-product-img="${key}" referrerpolicy="no-referrer" loading="eager"></span>`}
function task(d,id,label,key,sub){const yes=doneSet(d).has(id);const full=PRODUCTS[key]?.name||label;return `<button type="button" class="task ${yes?'done':''}" data-day="${d}" data-id="${id}" aria-label="${full}"><span class="tick">${yes?'✓':''}</span>${imgTag(key)}<span class="task-copy"><b>${full}</b><small>${sub}</small></span></button>`}
function repairImages(){document.querySelectorAll('[data-product-img]').forEach(img=>{img.onerror=()=>{img.onerror=null;img.closest('.task-img')?.classList.add('image-failed');img.style.opacity='.25'};if(img.complete&&img.naturalWidth===0)img.onerror()})}
function today(){const d=previewDay||currentDay(),r=routine(d),ds=doneSet(d),m=r.morning.filter(x=>ds.has(x[0])).length,n=r.night.filter(x=>ds.has(x[0])).length,p=pct(d);return `<div class="home" id="home"><header class="home-head"><div><div class="eyebrow">${previewDay?'PLAN PREVIEW':'TODAY'}</div><h2>${previewDay?'Routine':'Good day'} <span>· ${planDate(d)}</span></h2><p>${p===100?'All done — great job! 🎉':p>0?'Keep going. You are on track.':'One simple step at a time.'}</p></div><div class="day-ring"><strong>${d}</strong><small>/30</small></div></header><section class="progress-strip"><div><strong>${p}%</strong><small>today</small></div><div class="progress-line"><i style="width:${p}%"></i></div><div class="stat"><strong>${streak()}</strong><small>streak</small></div></section><section class="routine-stack"><div class="routine-card morning"><div class="routine-head"><span class="routine-icon">☀️</span><div><b>Morning</b><small>${m}/4 complete</small></div></div><div class="task-grid">${r.morning.map(x=>task(d,...x)).join('')}</div></div><div class="routine-card night"><div class="routine-head"><span class="routine-icon">🌙</span><div><b>Night</b><small>${n}/3 · ${az(d)?'Azelaic':'Niacinamide'}</small></div></div><div class="task-grid night-grid">${r.night.map(x=>task(d,...x)).join('')}</div></div></section></div>`}
function moveDay(delta){let d=previewDay||currentDay();d=Math.max(1,Math.min(30,d+delta));previewDay=d===currentDay()?null:d;render('today')}
function days(){const cd=currentDay();return `<div class="tab"><header><div><div class="eyebrow">YOUR PLAN</div><h2>30 Days</h2><p>Tap any day to preview its routine.</p></div><span class="chip">${completedDays()}/30 done</span></header><div class="days-grid">${Array.from({length:30},(_,i)=>{const n=i+1,p=pct(n);return `<button type="button" class="day-card ${p===100?'done':''} ${n===cd?'today':''}" data-preview="${n}"><strong>${n}</strong><small>${p===100?'✓':p+'%'}</small></button>`}).join('')}</div><div class="tab-note">🌙 Azelaic nights: ${AZELAIC_DAYS.join(', ')} · other nights use Niacinamide.</div></div>`}
function photoCard(d){const has=!!state.photoDays[d],due=currentDay()>=d&&!has&&PHOTO_MILESTONES.includes(d);return `<div class="photo-card"><div class="photo-label-wrap"><span class="photo-label">Day ${d}</span>${due?'<span class="red-dot" title="Photo reminder"></span>':''}</div><button type="button" class="photo-box ${has?'has-photo':''}" id="photo-${d}" data-photo-view="${d}" aria-label="Day ${d} progress photo">${has?'Loading…':`<span class="photo-placeholder">Day ${d}<small>Tap to add</small></span>`}</button>${has?`<div class="photo-actions"><button type="button" class="photo-btn" data-photo="${d}">Replace</button><button type="button" class="remove-btn" data-remove-photo="${d}">Remove</button></div>`:''}</div>`}
function progress(){const cd=completedDays(),p=Math.round(cd/30*100),due=photoReminderDue();return `<div class="tab progress-tab"><header><div><div class="eyebrow">YOUR PROGRESS</div><h2>Progress ${due?'<span class="red-dot-inline"></span>':''}</h2><p>${due?'📸 Photo reminder — add your milestone photo.':'Keep your routine consistent.'}</p></div><span class="chip">${p}%</span></header><section class="progress-card"><div class="big-number"><strong>${cd}</strong><small>/30 days</small></div><div><b>Completed days</b><small>🔥 ${streak()} day streak</small></div><div class="progress-line wide"><i style="width:${p}%"></i></div></section><div class="photo-title"><b>📸 Progress photos</b><small>Day 1 · 5 · 10 · 20 · 25 · 30</small></div><div class="photos">${[1,5,10,20,25,30].map(photoCard).join('')}</div><div class="tab-note">A red dot marks a 5-day photo reminder when a milestone photo is still missing.</div></div>`}
async function render(tab=currentTab){if(tab)currentTab=tab;document.querySelectorAll('.nav-item').forEach(b=>{b.classList.toggle('active',b.dataset.tab===currentTab);b.classList.toggle('reminder',b.dataset.tab==='progress'&&photoReminderDue())});const s=document.getElementById('screen');s.innerHTML=currentTab==='today'?today():currentTab==='days'?days():progress();applyTheme();repairImages();if(currentTab==='progress')await hydratePhotos()}
function applyTheme(){document.documentElement.dataset.theme=state.theme||'light';updateTheme()}
function updateTheme(){const b=document.getElementById('themeBtn');if(b)b.textContent=state.theme==='dark'?'☀️ Day mode':'🌙 Dark mode';const q=document.getElementById('quickThemeBtn');if(q){q.textContent=state.theme==='dark'?'☀️':'🌙';q.title=state.theme==='dark'?'Tap to day mode':'Tap to dark mode';q.setAttribute('aria-label',q.title)}}
function openSettings(){document.getElementById('startDate').value=state.startDate;document.getElementById('morningTime').value=state.morningTime;document.getElementById('nightTime').value=state.nightTime;updateTheme();updateNotifyStatus();document.getElementById('modal').classList.remove('hidden')}
function closeSettings(){document.getElementById('modal').classList.add('hidden')}
function updateNotifyStatus(){const el=document.getElementById('notifyStatus'),btn=document.getElementById('notifyBtn');if(!('Notification'in window)){el.textContent='Notifications are not supported here';btn.textContent='🔔 Not supported';return}const p=Notification.permission;el.textContent=p==='granted'?'Notifications: ON ✓ — test below':'Notifications are '+(p==='denied'?'BLOCKED — allow this site in Chrome settings':'not enabled');btn.textContent=p==='granted'?'🔔 Send test notification':'🔔 Enable & Test notification'}
async function testNotification(){if(!('Notification'in window)){alert('Notifications are not supported in this browser.');return}if(Notification.permission==='denied'){alert('Notifications are blocked for this site. In Chrome: Site info → Permissions → Notifications → Allow.');return}const p=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(p!=='granted'){updateNotifyStatus();return}try{if(!navigator.serviceWorker.controller){const reg=await navigator.serviceWorker.ready;await reg.update()}const reg=await navigator.serviceWorker.ready;await reg.showNotification('Skin Routine ✓',{body:'Test notification from your Skin Routine app.',icon:'./icons/icon-192.png',badge:'./icons/icon-192.png',tag:'skin-test-v12',renotify:true});state.notifications=true;save();updateNotifyStatus()}catch(e){alert('Notification failed. Make sure this is the HTTPS GitHub Pages URL and Notifications are allowed for the site.')}}
function nextReminder(){const now=new Date(),arr=[];for(const[label,t]of[['Morning',state.morningTime],['Night',state.nightTime]]){const[h,m]=t.split(':').map(Number),x=new Date(now);x.setHours(h,m,0,0);if(x<=now)x.setDate(x.getDate()+1);arr.push([x,label])}arr.sort((a,b)=>a[0]-b[0]);return arr[0]}
function scheduleNext(){clearTimeout(timer);if(Notification.permission!=='granted')return;const[when,label]=nextReminder();timer=setTimeout(async()=>{try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(label+' skincare',{body:'Time for your '+label.toLowerCase()+' routine.',icon:'./icons/icon-192.png',badge:'./icons/icon-192.png',tag:'skin-'+label.toLowerCase(),renotify:true})}catch{}scheduleNext()},Math.max(1000,when-Date.now()))}
function checkMissed(){if(Notification.permission!=='granted')return;const now=new Date(),todayKey=iso();for(const[label,t]of[['Morning',state.morningTime],['Night',state.nightTime]]){const[h,m]=t.split(':').map(Number),stamp=todayKey+'-'+label;if(now.getHours()>h||now.getHours()===h&&now.getMinutes()>=m){if(state.lastReminder[stamp])continue;state.lastReminder[stamp]=Date.now();save();if((label==='Morning'&&pct(currentDay())<40)||(label==='Night'&&pct(currentDay())<100)){navigator.serviceWorker.ready.then(reg=>reg.showNotification(label+' skincare reminder',{body:'Your '+label.toLowerCase()+' routine is waiting for you.',icon:'./icons/icon-192.png',badge:'./icons/icon-192.png',tag:'missed-'+label.toLowerCase()})).catch(()=>{})}}}}
async function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(PHOTO_DB,1);q.onupgradeneeded=()=>q.result.createObjectStore(PHOTO_STORE);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}async function putPhoto(d,b){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(PHOTO_STORE,'readwrite');t.objectStore(PHOTO_STORE).put(b,String(d));t.oncomplete=()=>{db.close();res()};t.onerror=()=>rej(t.error)})}async function getPhoto(d){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(PHOTO_STORE).objectStore(PHOTO_STORE).get(String(d));q.onsuccess=()=>{db.close();res(q.result)};q.onerror=()=>rej(q.error)})}async function delPhoto(d){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(PHOTO_STORE,'readwrite');t.objectStore(PHOTO_STORE).delete(String(d));t.oncomplete=()=>{db.close();res()};t.onerror=()=>rej(t.error)})}async function hydratePhotos(){for(const d of[1,5,10,20,25,30])if(state.photoDays[d]){try{const b=await getPhoto(d),box=document.getElementById('photo-'+d);if(b&&box){if(urls[d])URL.revokeObjectURL(urls[d]);urls[d]=URL.createObjectURL(b);box.innerHTML=`<img src="${urls[d]}" alt="Day ${d}">`}}catch{}}}async function removePhoto(d){await delPhoto(d).catch(()=>{});delete state.photoDays[d];save();render('progress')}function choosePhoto(d){photoTarget=d;const i=document.getElementById('photoInput');i.value='';i.click()}function compress(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1200,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>b?res(b):rej(), 'image/jpeg',.82)};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(f)})}
async function openPhotoViewer(d){try{const b=await getPhoto(d);if(!b)return;const u=URL.createObjectURL(b);const overlay=document.createElement('div');overlay.className='photo-viewer';overlay.innerHTML=`<button class="photo-viewer-close" aria-label="Close">✕</button><img src="${u}" alt="Day ${d} progress photo"><div class="photo-viewer-title">Day ${d}</div>`;document.body.appendChild(overlay);const close=()=>{URL.revokeObjectURL(u);overlay.remove()};overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('.photo-viewer-close'))close()});}catch{alert('Unable to open this photo.')}}
const input=document.getElementById('photoInput');input.onchange=async e=>{const f=e.target.files?.[0];if(!f||!photoTarget)return;try{await putPhoto(photoTarget,await compress(f));state.photoDays[photoTarget]=true;save();render('progress')}catch{alert('Photo save failed. Please try another image.')}};
const screen=document.getElementById('screen');screen.addEventListener('click',e=>{if(productHoldTriggered){productHoldTriggered=false;return}const view=e.target.closest('[data-photo-view]');if(view){const d=Number(view.dataset.photoView);if(state.photoDays[d]){openPhotoViewer(d)}else{choosePhoto(d)}return}const t=e.target.closest('[data-id]');if(t){toggle(Number(t.dataset.day),t.dataset.id);return}const day=e.target.closest('[data-preview]');if(day){previewDay=Number(day.dataset.preview);render('today');return}const photo=e.target.closest('[data-photo]');if(photo){choosePhoto(Number(photo.dataset.photo));return}const rem=e.target.closest('[data-remove-photo]');if(rem){removePhoto(Number(rem.dataset.removePhoto));return}});
screen.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX},{passive:true});screen.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(currentTab==='today'&&Math.abs(dx)>60)moveDay(dx<0?1:-1)},{passive:true});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{previewDay=null;render(b.dataset.tab)});document.getElementById('quickThemeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};document.getElementById('settingsBtn').onclick=openSettings;document.getElementById('closeModal').onclick=closeSettings;document.getElementById('startDate').onchange=e=>{state.startDate=e.target.value;save();previewDay=null;render('today')};document.getElementById('morningTime').onchange=e=>{state.morningTime=e.target.value;save();scheduleNext()};document.getElementById('nightTime').onchange=e=>{state.nightTime=e.target.value;save();scheduleNext()};document.getElementById('themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};document.getElementById('notifyBtn').onclick=testNotification;document.getElementById('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else alert('Chrome menu → Install app / Add to Home screen ഉപയോഗിക്കുക.')};document.getElementById('resetBtn').onclick=async()=>{if(confirm('Reset routine progress and photos?')){for(const d of[1,5,10,15,20,25,30])await delPhoto(d).catch(()=>{});const keep={startDate:state.startDate,morningTime:state.morningTime,nightTime:state.nightTime,theme:state.theme};state={...def(),...keep};save();closeSettings();render('today')}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.addEventListener('focus',()=>{scheduleNext();checkMissed()});
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{try{const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs)await r.update();await navigator.serviceWorker.register('service-worker.js?v=12',{scope:'./'});const reg=await navigator.serviceWorker.ready;reg.update()}catch{}});

function openProductViewer(key){const p=PRODUCTS[key];if(!p)return;const overlay=document.createElement('div');overlay.className='product-viewer';overlay.innerHTML=`<button class="product-viewer-close" aria-label="Close">✕</button><img src="${p.img}" alt="${p.name}" referrerpolicy="no-referrer"><div class="product-viewer-title">${p.name}</div>`;document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('.product-viewer-close'))close()})}
let productHoldTimer=null,productHoldTriggered=false;
screen.addEventListener('pointerdown',e=>{const img=e.target.closest('[data-product-img]');if(!img)return;productHoldTimer=setTimeout(()=>{productHoldTriggered=true;openProductViewer(img.dataset.productImg)},500)});
['pointerup','pointercancel','pointerleave'].forEach(ev=>screen.addEventListener(ev,()=>{clearTimeout(productHoldTimer);productHoldTimer=null}));
['copy','cut','contextmenu'].forEach(ev=>document.addEventListener(ev,e=>{if(e.target.matches('input,textarea,[contenteditable="true"]'))return;e.preventDefault()}));
document.addEventListener('selectstart',e=>{if(e.target.matches('input,textarea,[contenteditable="true"]'))return;e.preventDefault()});
applyTheme();render('today');scheduleNext();checkMissed();
